oss backend support profile
xiaozhu36/terraform pull request #10
Opened 2019-07-31 08:36 UTC by YY-tomorrow

2019-07-31 10:27 UTC, xiaozhu36 requested changes

2019-07-31 10:27 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> +				Description: "The path to the shared credentials file. If not set this defaults to ~/.aliyun/config.json",
This is the path to the shared credentials file. If this is not set, ~/.aliyun/config.json will be used.

2019-07-31 10:27 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> +				Description: "The profile for API operations. If not set, the default profile created with `aliyun configure` will be used.",
This is the Alibaba Cloud profile name as set in the shared credentials file. If not set, the default profile created with `aliyun configure` will be used.

2019-07-31 10:27 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> -					DefaultFunc: schema.EnvDefaultFunc("ALICLOUD_ASSUME_ROLE_SESSION_NAME", "terraform"),
why removed?

2019-07-31 10:27 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
>   * `assume_role` - (Optional) If provided with a role ARN, will attempt to assume this role using the supplied credentials.
still applies

2019-07-31 10:44 UTC, YY-tomorrow commented on backend/remote-state/oss/backend.go
> -					DefaultFunc: schema.EnvDefaultFunc("ALICLOUD_ASSUME_ROLE_SESSION_NAME", "terraform"),
默认取terraform，后面的从profile取值，无法判断是默认值还是用户填入的值

2019-08-05 23:08 UTC, xiaozhu36 requested changes

2019-08-05 23:08 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> +					Description: "The role to be assumed",
这个为啥改成Optional？
Description不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> +					Description: "The permissions applied when assuming a role.",
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
> -
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
> -  Terraform executes configuration on account with provided credentials.
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
> -  security credentials. You cannot use this policy to grant permissions which exceed those of the role that is being assumed.
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
> +* `session_name` - (Optional) The session name to use when assuming the role. It supports environment variable `ALICLOUD_ASSUME_ROLE_SESSION_NAME`.
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on website/docs/backends/types/oss.html.md
> +* `session_expiration` - (Optional) The time after which the established session for assuming role expires. It supports environment variable `ALICLOUD_ASSUME_ROLE_SESSION_EXPIRATION`.
不用改

2019-08-05 23:08 UTC, xiaozhu36 commented on backend/remote-state/oss/backend.go
> +	var getConfigFromProfileByKey = func(str string, key string) string {
getConfigFromProfileByKey 改为 getBackendConfig

2019-08-06 02:40 UTC, xiaozhu36 approved these changes

2019-08-06 02:40 UTC, merged